generic-kafka:
  image:
    repository: ghcr.io/miletocarmelo/finance_price_streamer
    tag: latest
  
  application:
    type: "producer"
    config:
      defaultSymbol: "JPY"
      defaultDays: "3"
      defaultSpeed: "1.0"

  kafka:
    topics:
      - name: "price-data"
        partitions: 3
        replicationFactor: 1