kafka-app:
  image:
    repository: ghcr.io/miletocarmelo/finance_price_streamer
    tag: latest
    pullPolicy: Always

  kafka:
    servers: "kafka-dev-service.kafka-dev:9092"  # Mise à jour de l'adresse Kafka
    topics:
      - name: "price-data"
        partitions: 3
        replicationFactor: 1

  application:
    type: "producer"
    config:
      defaultSymbol: "JPY"
      defaultDays: "3"
      defaultSpeed: "1.0"

  # Ajout des sondes de santé
  probes:
    livenessProbe:
      httpGet:
        path: /health/live
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /health/ready  
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10

  # Configuration du port
  ports:
    - name: http
      containerPort: 8000
      protocol: TCP