kafka-app:
  image:
    repository: ghcr.io/miletocarmelo/finance_price_streamer
    tag: latest
    pullPolicy: Always

  # env:
  #   - name: KAFKA_SERVERS
  #     value: "kafka-dev-service.kafka-dev:9092"
  #   - name: DEFAULT_SYMBOL
  #     value: "JPY"
  #   - name: DEFAULT_DAYS
  #     value: "3"
  #   - name: DEFAULT_SPEED
  #     value: "1.0"
  #   - name: KAFKA_TOPIC
  #     value: "price-data"
  
  kafka:
    # servers: "kafka-dev-service.kafka-dev:9092"
    servers: "kafka-dev-service.kafka-dev.svc.cluster.local:9092"
    consumer:
      groupId: "default-group"
      autoOffsetReset: "earliest"
      enableAutoCommit: true
    topics:
      - name: "price-data"
        partitions: 3
        replicationFactor: 1

  application:
    type: "producer"
    config:
      defaultSymbol: "JPY"
      defaultDays: "3"
      defaultSpeed: "1.0"
      customConfig:
        KAFKA_TOPIC: "price-data"

  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  probes:
    livenessProbe:
      httpGet:
        path: /health/live
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /health/ready
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

  ports:
    - name: http
      containerPort: 8000
      protocol: TCP

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0