generic-kafka-app:
  image:
    repository: ghcr.io/miletocarmelo/finance_price_streamer
    tag: latest
    pullPolicy: Always

  kafka:
    servers: "kafka-dev-kafka-bootstrap.kafka-dev:9092"
    topics:
      - name: "price-data"
        partitions: 3
        replicationFactor: 1

  application:
    type: "producer"
    config:
      defaultSymbol: "JPY"
      defaultDays: "3"
      defaultSpeed: "1.0"